"""empty message

Revision ID: 2c17d6939f92
Revises: 2f3d723e5c52
Create Date: 2025-01-28 07:51:52.911935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c17d6939f92'
down_revision: Union[str, None] = '2f3d723e5c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workout_new',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('title', sa.String, nullable=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('hevy_app_id', sa.VARCHAR, nullable=True),
        sa.Column('true_coach_id', sa.Integer, nullable=True),
        sa.ForeignKeyConstraint(['hevy_app_id'], ['HevyAppWorkout.id']),
        sa.ForeignKeyConstraint(['true_coach_id'], ['TrueCoachWorkout.id']),
        sa.UniqueConstraint('hevy_app_id', 'true_coach_id', name='_hevy_app_true_coach_uc'),
        sa.UniqueConstraint('hevy_app_id', name='_hevy_app_uc'),
        sa.UniqueConstraint('true_coach_id', name='_true_coach_uc')

    )

    # Copy data from the old Workout table to the new table
    op.execute("""
        INSERT INTO workout_new (id, title, description, hevy_app_id, true_coach_id)
        SELECT id, title, description, hevy_app_id, true_coach_id
        FROM Workout
    """)

    # Drop the old Workout table
    op.drop_table('Workout')

    # Rename the new Workout table to the original table name
    op.rename_table('workout_new', 'Workout')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_true_coach_uc', 'Workout', type_='unique')
    op.drop_constraint('_hevy_app_uc', 'Workout', type_='unique')
    op.alter_column('Workout', 'hevy_app_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
