"""empty message

Revision ID: 2f3d723e5c52
Revises: 
Create Date: 2025-01-28 07:32:12.079007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3d723e5c52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     # Create a new table with the desired schema
    op.create_table(
        'hevy_app_workout_item_new',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('workout_id', sa.Integer, nullable=False),
        sa.Column('index', sa.Integer, nullable=False),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('notes', sa.String, nullable=False),
        sa.Column('superset_id', sa.Integer, default=False),
        sa.Column('exercise_id', sa.String, nullable=True),
        sa.ForeignKeyConstraint(['workout_id'], ['HevyAppWorkout.id']),
        sa.ForeignKeyConstraint(['exercise_id'], ['HevyAppExercise.id']),
        sa.UniqueConstraint('workout_id', 'index', name='_hevy_app_workout_index_uc')
    )

    # Copy data from the old table to the new table
    op.execute("""
        INSERT INTO hevy_app_workout_item_new (id, workout_id, "index", name, notes, superset_id, exercise_id)
        SELECT id, workout_id, "index", name, notes, superset_id, exercise_id
        FROM HevyAppWorkoutItem
    """)

    # Drop the old table
    op.drop_table('HevyAppWorkoutItem')

    # Rename the new table to the original table name
    op.rename_table('hevy_app_workout_item_new', 'HevyAppWorkoutItem')
    # Create a new table with the desired schema for Workout
    op.create_table(
        'workout_new',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('title', sa.String, nullable=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('hevy_app_id', sa.VARCHAR, nullable=True),
        sa.Column('true_coach_id', sa.Integer, nullable=True),
        sa.ForeignKeyConstraint(['hevy_app_id'], ['HevyAppWorkout.id']),
        sa.ForeignKeyConstraint(['true_coach_id'], ['TrueCoachWorkout.id']),
        sa.UniqueConstraint('hevy_app_id', 'true_coach_id', name='_hevy_app_true_coach_uc')
    )

    # Copy data from the old Workout table to the new table
    op.execute("""
        INSERT INTO workout_new (id, title, description, hevy_app_id, true_coach_id)
        SELECT id, title, description, hevy_app_id, true_coach_id
        FROM Workout
    """)

    # Drop the old Workout table
    op.drop_table('Workout')

    # Rename the new Workout table to the original table name
    op.rename_table('workout_new', 'Workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Workout', type_='foreignkey')
    op.drop_constraint(None, 'Workout', type_='foreignkey')
    op.drop_constraint('_hevy_app_true_coach_uc', 'Workout', type_='unique')
    op.alter_column('Workout', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Workout', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('HevyAppWorkoutItem', 'workout_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('hevy_app_workout',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hevy_app_workout_item_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.VARCHAR(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=False),
    sa.Column('superset_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['hevy_app_exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['hevy_app_workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'index', name='_hevy_app_workout_index_uc')
    )
    op.create_table('hevy_app_exercise',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
