"""empty message

Revision ID: 490a69a9a9ba
Revises: f561bbeed4d8
Create Date: 2025-02-10 13:15:20.956600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490a69a9a9ba'
down_revision: Union[str, None] = 'f561bbeed4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrueCoachAssessment',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('assessment_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('target_percentage', sa.String(), nullable=True),
    sa.Column('linked_assessment_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('true_coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['true_coach_id'], ['TrueCoachAssessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='_name_uc'),
    sa.UniqueConstraint('true_coach_id', name='_true_coach_uc')
    )
    op.create_table('TrueCoachAssessmentItem',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['TrueCoachAssessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MetricItem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('true_coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['Metric.id'], ),
    sa.ForeignKeyConstraint(['true_coach_id'], ['TrueCoachAssessmentItem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AppleHealthWorkoutType', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AppleHealthWorkoutType', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name', type_='unique')

    op.drop_table('MetricItem')
    op.drop_table('TrueCoachAssessmentItem')
    op.drop_table('Metric')
    op.drop_table('TrueCoachAssessment')
    # ### end Alembic commands ###
