"""empty message

Revision ID: 60efc009da5b
Revises: f34e1822f913
Create Date: 2025-02-10 15:00:47.965753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60efc009da5b'
down_revision: Union[str, None] = 'f34e1822f913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_workout_id_metric_id', ['workout_id', 'metric_id'])
        batch_op.create_foreign_key("_workout_id_fk", 'Workout', ['workout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.drop_constraint("_workout_id_fk", type_='foreignkey')
        batch_op.drop_constraint('_workout_id_metric_id', type_='unique')
        batch_op.drop_column('workout_id')

    # ### end Alembic commands ###
