"""empty message

Revision ID: 7b6e132f97ec
Revises: 2c17d6939f92
Create Date: 2025-01-30 07:55:03.290417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6e132f97ec'
down_revision: Union[str, None] = '2c17d6939f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Exercise')
    with op.batch_alter_table('Exercise', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_uc', ['name'])

    with op.batch_alter_table('Sets', schema=None) as batch_op:
        batch_op.create_unique_constraint('_workout_item_index_uc', ['workout_item_id', 'index'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sets', schema=None) as batch_op:
        batch_op.drop_constraint('_workout_item_index_uc', type_='unique')

    with op.batch_alter_table('Exercise', schema=None) as batch_op:
        batch_op.drop_constraint('_name_uc', type_='unique')

    op.create_table('_alembic_tmp_Exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('hevy_app_id', sa.VARCHAR(), nullable=True),
    sa.Column('true_coach_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['hevy_app_id'], ['HevyAppExercise.id'], ),
    sa.ForeignKeyConstraint(['true_coach_id'], ['TrueCoachExercise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hevy_app_id', 'true_coach_id', name='_hevy_app_true_coach_uc'),
    sa.UniqueConstraint('name', name='_name_uc')
    )
    # ### end Alembic commands ###
