"""empty message

Revision ID: 92f0ab8577b9
Revises: 7b6e132f97ec
Create Date: 2025-02-05 13:45:19.654356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f0ab8577b9'
down_revision: Union[str, None] = '7b6e132f97ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppleHealthDataType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'unit', name='uq_name_unit')
    )
    op.create_table('AppleHealthDataRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['data_type_id'], ['AppleHealthDataType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type_id', 'timestamp', name='uq_data_type_timestamp')
    )
    with op.batch_alter_table('AppleHealthDataRecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AppleHealthDataRecord_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('Workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Workout', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('AppleHealthDataRecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AppleHealthDataRecord_timestamp'))

    op.drop_table('AppleHealthDataRecord')
    op.drop_table('AppleHealthDataType')
    # ### end Alembic commands ###
