"""empty message

Revision ID: 98c7354b0525
Revises: 1592afc53e0d
Create Date: 2025-02-10 14:13:14.197307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c7354b0525'
down_revision: Union[str, None] = '1592afc53e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))

    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('Metric', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
