"""empty message

Revision ID: f34e1822f913
Revises: 98c7354b0525
Create Date: 2025-02-10 14:33:19.982195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34e1822f913'
down_revision: Union[str, None] = '98c7354b0525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_apple_id', ['apple_id'])
        batch_op.create_unique_constraint('_true_coach_id', ['true_coach_id'])
        batch_op.create_foreign_key("_apple_id_fk", 'AppleHealthDataRecord', ['apple_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MetricItem', schema=None) as batch_op:
        batch_op.drop_constraint("_apple_id_fk", type_='foreignkey')
        batch_op.drop_constraint('_true_coach_id', type_='unique')
        batch_op.drop_constraint('_apple_id', type_='unique')
        batch_op.drop_column('apple_id')

    # ### end Alembic commands ###
