"""empty message

Revision ID: f561bbeed4d8
Revises: 92f0ab8577b9
Create Date: 2025-02-05 17:19:42.559285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f561bbeed4d8'
down_revision: Union[str, None] = '92f0ab8577b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppleHealthWorkoutType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_name')
    )
    op.create_table('AppleHealthWorkout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workout_type_id'], ['AppleHealthWorkoutType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_type_id', 'start_date', 'end_date', name='uq_workout_type_start_date_end_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppleHealthWorkout')
    op.drop_table('AppleHealthWorkoutType')
    # ### end Alembic commands ###
